# Generated by Django 4.0.4 on 2022-05-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_customuser_password_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeektechDirections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
